FROM python:3.11-slim AS base

USER root

ENV TZ=Asia/Ho_Chi_Minh
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update -qq && \
    apt-get install -y \
    curl \
    telnet \
    wget \
    default-jre \
    build-essential\
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

COPY ./src /app/src
COPY ./settings /app/settings
RUN pip install --upgrade pip
COPY ./requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt && \
    pip install --no-cache-dir tqdm==4.66.2
RUN pip install google-api-python-client
RUN pip install google-generativeai
RUN chgrp -R 0 /app && chmod -R g=u /app

ENV PYTHONPATH "${PYTHONPATH}:/app"

WORKDIR /app


USER 1001

CMD ["python", "src/app.py"]
